var annotated_dup =
[
    [ "NNFS", "namespace_n_n_f_s.html", [
      [ "Activation", "class_n_n_f_s_1_1_activation.html", "class_n_n_f_s_1_1_activation" ],
      [ "Adagrad", "class_n_n_f_s_1_1_adagrad.html", "class_n_n_f_s_1_1_adagrad" ],
      [ "Adam", "class_n_n_f_s_1_1_adam.html", "class_n_n_f_s_1_1_adam" ],
      [ "CCE", "class_n_n_f_s_1_1_c_c_e.html", "class_n_n_f_s_1_1_c_c_e" ],
      [ "CCESoftmax", "class_n_n_f_s_1_1_c_c_e_softmax.html", "class_n_n_f_s_1_1_c_c_e_softmax" ],
      [ "Dense", "class_n_n_f_s_1_1_dense.html", "class_n_n_f_s_1_1_dense" ],
      [ "Layer", "class_n_n_f_s_1_1_layer.html", "class_n_n_f_s_1_1_layer" ],
      [ "Loss", "class_n_n_f_s_1_1_loss.html", "class_n_n_f_s_1_1_loss" ],
      [ "Metrics", "class_n_n_f_s_1_1_metrics.html", null ],
      [ "Model", "class_n_n_f_s_1_1_model.html", "class_n_n_f_s_1_1_model" ],
      [ "NeuralNetwork", "class_n_n_f_s_1_1_neural_network.html", "class_n_n_f_s_1_1_neural_network" ],
      [ "Optimizer", "class_n_n_f_s_1_1_optimizer.html", "class_n_n_f_s_1_1_optimizer" ],
      [ "ReLU", "class_n_n_f_s_1_1_re_l_u.html", "class_n_n_f_s_1_1_re_l_u" ],
      [ "RMSProp", "class_n_n_f_s_1_1_r_m_s_prop.html", "class_n_n_f_s_1_1_r_m_s_prop" ],
      [ "SGD", "class_n_n_f_s_1_1_s_g_d.html", "class_n_n_f_s_1_1_s_g_d" ],
      [ "Sigmoid", "class_n_n_f_s_1_1_sigmoid.html", "class_n_n_f_s_1_1_sigmoid" ],
      [ "Softmax", "class_n_n_f_s_1_1_softmax.html", "class_n_n_f_s_1_1_softmax" ],
      [ "Tanh", "class_n_n_f_s_1_1_tanh.html", "class_n_n_f_s_1_1_tanh" ]
    ] ],
    [ "AdagradTest", "class_adagrad_test.html", "class_adagrad_test" ],
    [ "AdamTest", "class_adam_test.html", "class_adam_test" ],
    [ "CCESoftmaxTest", "class_c_c_e_softmax_test.html", "class_c_c_e_softmax_test" ],
    [ "CCETest", "class_c_c_e_test.html", "class_c_c_e_test" ],
    [ "DenseTest", "class_dense_test.html", "class_dense_test" ],
    [ "MetricsTest", "class_metrics_test.html", "class_metrics_test" ],
    [ "OptimizerTest", "class_optimizer_test.html", "class_optimizer_test" ],
    [ "ReLUTest", "class_re_l_u_test.html", "class_re_l_u_test" ],
    [ "RMSpropTest", "class_r_m_sprop_test.html", "class_r_m_sprop_test" ],
    [ "SGDTest", "class_s_g_d_test.html", "class_s_g_d_test" ],
    [ "SigmoidTest", "class_sigmoid_test.html", "class_sigmoid_test" ],
    [ "SoftmaxTest", "class_softmax_test.html", "class_softmax_test" ],
    [ "TanhTest", "class_tanh_test.html", "class_tanh_test" ]
];